### ISSUE TITLE
Not preloading subdomains

### ISSUE THREAD

**Issue by jp26jp** [luehrsenheinrich/wp-quicklink#18]
### What happened?
It's not preloading subdomains.

### How can we reproduce this behavior?

Can you provide a link to a page which shows this issue?
If you go to [this page](https://theperry.group/) and hover over the "Property" menu option, it won't preload the subdomain URL options.

### Technical info
* WordPress version: 5.1.1
* quicklink version: 0.5.0

**Comment by westonruter** [comment]
This should be entirely expected because the only whitelisted origin by default is from `home_url()`:

https://github.com/luehrsenheinrich/wp-quicklink/blob/b572791cb477ef3733e31145ad2218b6dbcf8734/build/quicklink.php#L52-L55

If you want to include other subdomains, you can do this in a custom plugin or a theme's `functions.php`:

```php
add_filter(
	'quicklink_options',
	function ( $options ) {
		$options['origins'] = 'my-subdomain.example.com';
		return $options;
	}
);
```
